name: scan
on:
  workflow_dispatch:
jobs:
  build:
    name: Scan
    runs-on: ubuntu-20.04
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/virtocommerce/platform:3.817.0-alpha.12888-vcst-567-contacts-redesign-dcacccf1'
          format: 'json'
          exit-code: '0'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: ./3.817.0-alpha.12888-vcst-567-contacts-redesign-dcacccf1.json
      - run: |
          cat ./3.817.0-alpha.12888-vcst-567-contacts-redesign-dcacccf1.json
      - name: Publish file
        uses: actions/upload-artifact@v2
        with:
          name: trivy.json
          path: ./3.817.0-alpha.12888-vcst-567-contacts-redesign-dcacccf1.json
      - run: |
          
