name: scan
on:
  workflow_dispatch:
jobs:
  build:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      tag: '3.809.0-alpha.12863-dev-06cf1fbb'
      # VULN_PACKAGES: ''
      # VULN_CVES: ''
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/virtocommerce/platform:${{ env.tag }}'
          format: 'json'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: './${{ env.tag }}.json'
      # - run: |
      #     cat './${{ env.tag }}.json'
      - name: Publish file
        uses: actions/upload-artifact@v2
        with:
          name: '${{ env.tag }}.json'
          path: './${{ env.tag }}.json'
      - name: Process results
        id: trivyResult
        shell: pwsh
        run: |
          $report = Get-Content './${{ env.tag }}.json' -Raw | ConvertFrom-Json
          $i = 0
          $reportHash = @{}
          $cve = @()
          while($i -lt $report.Results.Vulnerabilities.Count){
              # if($cve -notcontains $report.Results.Vulnerabilities.VulnerabilityID[$i]){
              #     $cve += $($report.Results.Vulnerabilities.VulnerabilityID[$i])
              # }
              if($reportHash.Keys -notcontains $report.Results.Vulnerabilities[$i].PkgName){
                  $reportHash.Add($($report.Results.Vulnerabilities[$i].PkgName),$($report.Results.Vulnerabilities[$i].FixedVersion))
              }
              $i += 1
          }
          $packages = $reportHash.GetEnumerator() | Sort-Object Name
          # $cves = $cve.GetEnumerator() | Sort-Object -Descending
          # echo $packages
          # echo $cves
          echo "::set-output name=VULN_PACKAGES::$packages" >> $GITHUB_OUTPUT
          # echo "VULN_CVES=$cves" >> $GITHUB_OUTPUT
      - run: |
          echo "VULN_PACKAGES: ${{ steps.trivyResult.outputs.VULN_PACKAGES }}"
          # echo "VULN_CVES: ${{ steps.trivyResult.outputs.VULN_CVES }}"
          
