name: Remove stale branches

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *" # Everday at midnight

jobs:
  remove-stale-branches:
    name: Remove Stale Branches
    runs-on: ubuntu-latest
    steps:
      - uses: fpicalausa/remove-stale-branches@v2.1.2
        with:
          # dry-run: true # Check out the console output before setting this to false
          days-before-branch-stale: 14
          exempt-branches-regex: "^(main|master|dev)$"
          operations-per-run: 100
          github-token: ${{ secrets.GH_TOKEN }}
          ignore-branches-with-open-prs: true
